// The topology page's `?mock=1` projection, and the fixture tier's data.
//
// NOT a copy of either committed topology. A deliberately small mechanism that
// exercises every state the rails and the grid have to render honestly: a
// branch point with a fan-out, a grounded loop that closes with a curve back up,
// a `gap` edge, a DERIVED gap that carries no value at all, a linear-to-rotary
// coupling, all four provenance states including an element with no citation,
// a zero-width band, the three crop states, and a study that raises
// BranchAmbiguity instead of summing. The two committed topologies are covered
// by the node-fs tier, which reads the real projection.
//
// EVERY NUMBER IN HERE CAME OUT OF THE REAL BUILDER. It was generated by running
// scripts/build_topology_projection.py's own project_topology() over the demo
// documents and pasting the result, so no total in this file is one
// tolerance_stack.topology.summarize() would not produce. Regenerate it the same
// way if the projection's shape changes -- do not hand-edit a number.
//
// The three `crop_key`s are the one thing patched in afterwards: crop_key is
// derived from a dimension_ref into a real stack file and the demo mechanism has
// no stack behind it, so the fixture states the three states directly and
// addresses the demo crops index in fixtures.js. Same licence the stack fixture
// takes with its `unestablished` export, which no live citation carries either.
//
// The numbers are arbitrary and internally consistent with a fold; nothing here
// is a claim about any Joby part.
(function (VA) {
  "use strict";

  VA.demoTopologyProjection = function () {
    return {
      schema: "joby.tolerance_stack/topology_projection/v0",
      built_at: "2026-08-05T00:00:00+00:00",
      built_by: "scripts/build_topology_projection.py",
      // Stamped from the SAME tree as the crops fixture, clean and level with
      // trunk -- the quiet case, so ?mock=1 shows the provenance line without
      // the alarm. The alarms have their own tests, which build the disagreeing
      // pair inline.
      provenance: VA.demoProvenance("scripts/build_topology_projection.py"),
      topologies_dir: "docs/topologies",
      row_kinds: ["node", "edge"],
      link_kinds: ["branch", "close"],
      value_sources: ["inline", "stack_ref", "derived"],
      study_statuses: ["ok", "error"],
      topologies: [
      {
        "id": "demo_mechanism",
        "title": "Demo mechanism - a fork, a loop, a gap and a coupling",
        "units": "mm",
        "source_file": "docs/topologies/topology_demo_mechanism.json",
        "topology": {
          "schema": "joby.tolerance_stack/topology/v0",
          "id": "demo_mechanism",
          "title": "Demo mechanism - a fork, a loop, a gap and a coupling",
          "units": "mm",
          "transforms": [
            {
              "id": "arm_linear_to_rotary",
              "kind": "linear_to_rotary",
              "ratio": 2.5,
              "units_in": "mm",
              "units_out": "deg",
              "source_ref": {
                "kind": "assumed",
                "confidence": "untraced",
                "note": "PLACEHOLDER - an invented sensitivity."
              }
            }
          ],
          "parts": [
            {
              "id": "base",
              "name": "base plate",
              "drawing": "215197"
            },
            {
              "id": "post",
              "name": "post"
            },
            {
              "id": "arm",
              "name": "arm"
            },
            {
              "id": "strut",
              "name": "parallel strut",
              "note": "identity not established"
            }
          ],
          "nodes": [
            {
              "id": "base_datum",
              "name": "base datum face",
              "parts": [
                "base"
              ],
              "kind": "datum_feature"
            },
            {
              "id": "base_post_seat",
              "name": "base / post seat",
              "parts": [
                "base",
                "post"
              ],
              "kind": "mating_surface"
            },
            {
              "id": "post_arm_pin",
              "name": "post / arm pin",
              "parts": [
                "post",
                "arm"
              ],
              "kind": "mating_surface"
            },
            {
              "id": "arm_tip",
              "name": "arm tip",
              "parts": [
                "arm"
              ],
              "kind": "datum_feature"
            },
            {
              "id": "post_strut_bushing",
              "name": "post / strut bushing",
              "parts": [
                "post",
                "strut"
              ],
              "kind": "mating_surface"
            },
            {
              "id": "strut_end",
              "name": "strut far end",
              "parts": [
                "strut"
              ],
              "kind": "datum_feature"
            }
          ],
          "edges": [
            {
              "id": "base_thickness",
              "name": "base plate thickness",
              "kind": "structural",
              "part": "base",
              "from": "base_datum",
              "to": "base_post_seat",
              "dimension": {
                "id": "base_thickness",
                "name": "base plate thickness",
                "nominal": 4.0,
                "min": 3.98,
                "max": 4.02,
                "plus_minus": 0.02,
                "role": "clamped_member",
                "source_ref": {
                  "kind": "drawing",
                  "document": "215197",
                  "revision": "A.1",
                  "sheet": 2,
                  "zone": "D10",
                  "callout": "4.00 +/-.02",
                  "confidence": "traced",
                  "export": {
                    "status": "established",
                    "pdf": "C:/workspace/demo/215197.pdf",
                    "sha256": "1111222233334444555566667777888899990000aaaabbbbccccddddeeeeffff",
                    "runs": []
                  }
                }
              }
            },
            {
              "id": "post_height",
              "name": "post height",
              "kind": "structural",
              "part": "post",
              "from": "base_post_seat",
              "to": "post_arm_pin",
              "dimension": {
                "id": "post_height",
                "name": "post height",
                "nominal": 10.0,
                "min": 9.9,
                "max": 10.1,
                "source_ref": {
                  "kind": "parts_list",
                  "document": "217755",
                  "sheet": 1,
                  "confidence": "inferred",
                  "note": "read off the parts list, not a dimensioned view.",
                  "export": {
                    "status": "unestablished",
                    "why": "three 217755 A.1 exports are in circulation and none hashes to the one this was read off"
                  }
                }
              }
            },
            {
              "id": "arm_pin_to_tip",
              "name": "arm pin to tip",
              "kind": "structural",
              "part": "arm",
              "from": "post_arm_pin",
              "to": "arm_tip",
              "transform": "arm_linear_to_rotary",
              "dimension": {
                "id": "arm_pin_to_tip",
                "name": "arm pin to tip",
                "nominal": 2.0,
                "min": 2.0,
                "max": 2.0,
                "source_ref": {
                  "kind": "workbook",
                  "document": "demo.xlsx",
                  "cell": "B7",
                  "confidence": "untraced",
                  "note": "PLACEHOLDER - a workbook cell that traces nothing, with a zero-width band on top."
                }
              }
            },
            {
              "id": "post_bushing_offset",
              "name": "post bushing offset",
              "kind": "structural",
              "part": "post",
              "from": "base_post_seat",
              "to": "post_strut_bushing",
              "dimension": {
                "id": "post_bushing_offset",
                "name": "post bushing offset",
                "nominal": 6.0,
                "min": 5.95,
                "max": 6.05
              }
            },
            {
              "id": "strut_length",
              "name": "strut length",
              "kind": "structural",
              "part": "strut",
              "from": "post_strut_bushing",
              "to": "strut_end",
              "dimension": {
                "id": "strut_length",
                "name": "strut length",
                "nominal": 8.0,
                "min": 7.9,
                "max": 8.1,
                "source_ref": {
                  "kind": "spec",
                  "document": "STRUT-DATASHEET.pdf",
                  "confidence": "traced"
                }
              }
            },
            {
              "id": "tip_to_strut_end",
              "name": "arm tip to strut end",
              "kind": "gap",
              "from": "arm_tip",
              "to": "strut_end"
            }
          ],
          "provenance": {
            "authored_by": "apps/viewer/fixtures.js - a demo, not a Joby part"
          },
          "notes": [
            "Every number here is invented. Nothing in this document is a claim about any hardware."
          ]
        },
        "parts": [
          {
            "id": "base",
            "name": "base plate",
            "drawing": "215197",
            "revision": null,
            "note": null
          },
          {
            "id": "post",
            "name": "post",
            "drawing": null,
            "revision": null,
            "note": null
          },
          {
            "id": "arm",
            "name": "arm",
            "drawing": null,
            "revision": null,
            "note": null
          },
          {
            "id": "strut",
            "name": "parallel strut",
            "drawing": null,
            "revision": null,
            "note": "identity not established"
          }
        ],
        "nodes": [
          {
            "id": "base_datum",
            "name": "base datum face",
            "kind": "datum_feature",
            "parts": [
              "base"
            ],
            "note": null,
            "source_ref": null,
            "confidence": null,
            "degree": 1,
            "branch": false
          },
          {
            "id": "base_post_seat",
            "name": "base / post seat",
            "kind": "mating_surface",
            "parts": [
              "base",
              "post"
            ],
            "note": null,
            "source_ref": null,
            "confidence": null,
            "degree": 3,
            "branch": true
          },
          {
            "id": "post_arm_pin",
            "name": "post / arm pin",
            "kind": "mating_surface",
            "parts": [
              "post",
              "arm"
            ],
            "note": null,
            "source_ref": null,
            "confidence": null,
            "degree": 2,
            "branch": false
          },
          {
            "id": "arm_tip",
            "name": "arm tip",
            "kind": "datum_feature",
            "parts": [
              "arm"
            ],
            "note": null,
            "source_ref": null,
            "confidence": null,
            "degree": 2,
            "branch": false
          },
          {
            "id": "post_strut_bushing",
            "name": "post / strut bushing",
            "kind": "mating_surface",
            "parts": [
              "post",
              "strut"
            ],
            "note": null,
            "source_ref": null,
            "confidence": null,
            "degree": 2,
            "branch": false
          },
          {
            "id": "strut_end",
            "name": "strut far end",
            "kind": "datum_feature",
            "parts": [
              "strut"
            ],
            "note": null,
            "source_ref": null,
            "confidence": null,
            "degree": 2,
            "branch": false
          }
        ],
        "edges": [
          {
            "id": "base_thickness",
            "name": "base plate thickness",
            "kind": "structural",
            "part": "base",
            "from": "base_datum",
            "to": "base_post_seat",
            "note": null,
            "properties": {},
            "value_source": "stack_ref",
            "dimension_ref": {
              "stack": "docs/tolerance_stacks/stack_demo_joint.json",
              "element": "plate"
            },
            "dimension": {
              "id": "base_thickness",
              "name": "base plate thickness",
              "nominal": 4.0,
              "min": 3.98,
              "max": 4.02,
              "role": "clamped_member",
              "lmc": null,
              "mmc": null,
              "plus_minus": 0.02,
              "hardware_ref": null,
              "source_ref": {
                "kind": "drawing",
                "document": "215197",
                "revision": "A.1",
                "sheet": 2,
                "zone": "D10",
                "view": null,
                "cell": null,
                "callout": "4.00 +/-.02",
                "export": {
                  "status": "established",
                  "pdf": "C:/workspace/demo/215197.pdf",
                  "sha256": "1111222233334444555566667777888899990000aaaabbbbccccddddeeeeffff",
                  "runs": [],
                  "why": null,
                  "note": null
                },
                "element_id": null,
                "run_id": null,
                "confidence": "traced",
                "note": null
              },
              "note": null
            },
            "confidence": "traced",
            "zero_width": false,
            "crop_key": {
              "stack": "demo_joint",
              "element": "plate"
            },
            "transform": {
              "id": "identity",
              "kind": "identity",
              "ratio": 1.0,
              "units_in": "mm",
              "units_out": "mm"
            },
            "transform_declared": null
          },
          {
            "id": "post_height",
            "name": "post height",
            "kind": "structural",
            "part": "post",
            "from": "base_post_seat",
            "to": "post_arm_pin",
            "note": null,
            "properties": {},
            "value_source": "stack_ref",
            "dimension_ref": {
              "stack": "docs/tolerance_stacks/stack_demo_joint.json",
              "element": "washer"
            },
            "dimension": {
              "id": "post_height",
              "name": "post height",
              "nominal": 10.0,
              "min": 9.9,
              "max": 10.1,
              "role": null,
              "lmc": null,
              "mmc": null,
              "plus_minus": null,
              "hardware_ref": null,
              "source_ref": {
                "kind": "parts_list",
                "document": "217755",
                "revision": null,
                "sheet": 1,
                "zone": null,
                "view": null,
                "cell": null,
                "callout": null,
                "export": {
                  "status": "unestablished",
                  "pdf": null,
                  "sha256": null,
                  "runs": [],
                  "why": "three 217755 A.1 exports are in circulation and none hashes to the one this was read off",
                  "note": null
                },
                "element_id": null,
                "run_id": null,
                "confidence": "inferred",
                "note": "read off the parts list, not a dimensioned view."
              },
              "note": null
            },
            "confidence": "inferred",
            "zero_width": false,
            "crop_key": {
              "stack": "demo_joint",
              "element": "washer"
            },
            "transform": {
              "id": "identity",
              "kind": "identity",
              "ratio": 1.0,
              "units_in": "mm",
              "units_out": "mm"
            },
            "transform_declared": null
          },
          {
            "id": "arm_pin_to_tip",
            "name": "arm pin to tip",
            "kind": "structural",
            "part": "arm",
            "from": "post_arm_pin",
            "to": "arm_tip",
            "note": null,
            "properties": {},
            "value_source": "inline",
            "dimension_ref": null,
            "dimension": {
              "id": "arm_pin_to_tip",
              "name": "arm pin to tip",
              "nominal": 2.0,
              "min": 2.0,
              "max": 2.0,
              "role": null,
              "lmc": null,
              "mmc": null,
              "plus_minus": null,
              "hardware_ref": null,
              "source_ref": {
                "kind": "workbook",
                "document": "demo.xlsx",
                "revision": null,
                "sheet": null,
                "zone": null,
                "view": null,
                "cell": "B7",
                "callout": null,
                "export": null,
                "element_id": null,
                "run_id": null,
                "confidence": "untraced",
                "note": "PLACEHOLDER - a workbook cell that traces nothing, with a zero-width band on top."
              },
              "note": null
            },
            "confidence": "untraced",
            "zero_width": true,
            "crop_key": null,
            "transform": {
              "id": "arm_linear_to_rotary",
              "kind": "linear_to_rotary",
              "ratio": 2.5,
              "units_in": "mm",
              "units_out": "deg"
            },
            "transform_declared": "arm_linear_to_rotary"
          },
          {
            "id": "post_bushing_offset",
            "name": "post bushing offset",
            "kind": "structural",
            "part": "post",
            "from": "base_post_seat",
            "to": "post_strut_bushing",
            "note": null,
            "properties": {},
            "value_source": "inline",
            "dimension_ref": null,
            "dimension": {
              "id": "post_bushing_offset",
              "name": "post bushing offset",
              "nominal": 6.0,
              "min": 5.95,
              "max": 6.05,
              "role": null,
              "lmc": null,
              "mmc": null,
              "plus_minus": null,
              "hardware_ref": null,
              "source_ref": null,
              "note": null
            },
            "confidence": "no_source_ref",
            "zero_width": false,
            "crop_key": null,
            "transform": {
              "id": "identity",
              "kind": "identity",
              "ratio": 1.0,
              "units_in": "mm",
              "units_out": "mm"
            },
            "transform_declared": null
          },
          {
            "id": "strut_length",
            "name": "strut length",
            "kind": "structural",
            "part": "strut",
            "from": "post_strut_bushing",
            "to": "strut_end",
            "note": null,
            "properties": {},
            "value_source": "stack_ref",
            "dimension_ref": {
              "stack": "docs/tolerance_stacks/stack_demo_joint.json",
              "element": "eye"
            },
            "dimension": {
              "id": "strut_length",
              "name": "strut length",
              "nominal": 8.0,
              "min": 7.9,
              "max": 8.1,
              "role": null,
              "lmc": null,
              "mmc": null,
              "plus_minus": null,
              "hardware_ref": null,
              "source_ref": {
                "kind": "spec",
                "document": "STRUT-DATASHEET.pdf",
                "revision": null,
                "sheet": null,
                "zone": null,
                "view": null,
                "cell": null,
                "callout": null,
                "export": null,
                "element_id": null,
                "run_id": null,
                "confidence": "traced",
                "note": null
              },
              "note": null
            },
            "confidence": "traced",
            "zero_width": false,
            "crop_key": {
              "stack": "demo_joint",
              "element": "eye"
            },
            "transform": {
              "id": "identity",
              "kind": "identity",
              "ratio": 1.0,
              "units_in": "mm",
              "units_out": "mm"
            },
            "transform_declared": null
          },
          {
            "id": "tip_to_strut_end",
            "name": "arm tip to strut end",
            "kind": "gap",
            "part": null,
            "from": "arm_tip",
            "to": "strut_end",
            "note": null,
            "properties": {},
            "value_source": "derived",
            "dimension_ref": null,
            "dimension": null,
            "confidence": null,
            "zero_width": false,
            "crop_key": null,
            "transform": {
              "id": "identity",
              "kind": "identity",
              "ratio": 1.0,
              "units_in": "mm",
              "units_out": "mm"
            },
            "transform_declared": null
          }
        ],
        "transforms": [
          {
            "id": "arm_linear_to_rotary",
            "kind": "linear_to_rotary",
            "ratio": 2.5,
            "units_in": "mm",
            "units_out": "deg",
            "source_ref": {
              "kind": "assumed",
              "document": null,
              "revision": null,
              "sheet": null,
              "zone": null,
              "view": null,
              "cell": null,
              "callout": null,
              "export": null,
              "element_id": null,
              "run_id": null,
              "confidence": "untraced",
              "note": "PLACEHOLDER - an invented sensitivity."
            },
            "properties": {},
            "note": null
          }
        ],
        "branch_nodes": [
          "base_post_seat"
        ],
        "layout": {
          "columns": 2,
          "rows": [
            {
              "row": 0,
              "kind": "node",
              "id": "base_datum",
              "column": 0,
              "branch": false
            },
            {
              "row": 1,
              "kind": "edge",
              "id": "base_thickness",
              "column": 0,
              "entered_at": "base_datum",
              "left_at": "base_post_seat",
              "closes_row": null,
              "closes_column": null
            },
            {
              "row": 2,
              "kind": "node",
              "id": "base_post_seat",
              "column": 0,
              "branch": true
            },
            {
              "row": 3,
              "kind": "edge",
              "id": "post_height",
              "column": 0,
              "entered_at": "base_post_seat",
              "left_at": "post_arm_pin",
              "closes_row": null,
              "closes_column": null
            },
            {
              "row": 4,
              "kind": "node",
              "id": "post_arm_pin",
              "column": 0,
              "branch": false
            },
            {
              "row": 5,
              "kind": "edge",
              "id": "arm_pin_to_tip",
              "column": 0,
              "entered_at": "post_arm_pin",
              "left_at": "arm_tip",
              "closes_row": null,
              "closes_column": null
            },
            {
              "row": 6,
              "kind": "node",
              "id": "arm_tip",
              "column": 0,
              "branch": false
            },
            {
              "row": 7,
              "kind": "edge",
              "id": "tip_to_strut_end",
              "column": 0,
              "entered_at": "arm_tip",
              "left_at": "strut_end",
              "closes_row": null,
              "closes_column": null
            },
            {
              "row": 8,
              "kind": "node",
              "id": "strut_end",
              "column": 0,
              "branch": false
            },
            {
              "row": 9,
              "kind": "edge",
              "id": "strut_length",
              "column": 0,
              "entered_at": "strut_end",
              "left_at": "post_strut_bushing",
              "closes_row": null,
              "closes_column": null
            },
            {
              "row": 10,
              "kind": "node",
              "id": "post_strut_bushing",
              "column": 0,
              "branch": false
            },
            {
              "row": 11,
              "kind": "edge",
              "id": "post_bushing_offset",
              "column": 1,
              "entered_at": "base_post_seat",
              "left_at": "post_strut_bushing",
              "closes_row": 10,
              "closes_column": 0
            }
          ],
          "rails": [
            {
              "column": 0,
              "start": 0,
              "end": 10
            },
            {
              "column": 1,
              "start": 2,
              "end": 11
            }
          ],
          "links": [
            {
              "kind": "branch",
              "row": 2,
              "from_column": 0,
              "to_row": 2,
              "to_column": 1
            },
            {
              "kind": "close",
              "row": 11,
              "from_column": 1,
              "to_row": 10,
              "to_column": 0
            }
          ]
        },
        "confidence_counts": {
          "traced": 2,
          "inferred": 1,
          "untraced": 1,
          "no_source_ref": 1
        },
        "notes": [
          "Every number here is invented. Nothing in this document is a claim about any hardware."
        ],
        "studies": [
          {
            "id": "demo_base_to_tip",
            "title": "Base datum to arm tip (degrees)",
            "topology": "demo_mechanism",
            "from": "base_datum",
            "to": "arm_tip",
            "closes": null,
            "selection": [
              "arm_pin_to_tip",
              "base_thickness",
              "post_height"
            ],
            "transforms": {
              "base_thickness": "arm_linear_to_rotary",
              "post_height": "arm_linear_to_rotary"
            },
            "source_file": "docs/topologies/study_demo_base_to_tip.json",
            "notes": [
              "Crosses the arm coupling, so every contributor is converted into degrees before anything is summed. Drop either override and summarize() raises UnitMismatch rather than adding millimetres to degrees."
            ],
            "provenance": {},
            "status": "ok",
            "error": null,
            "result": {
              "study": "demo_base_to_tip",
              "title": "Base datum to arm tip (degrees)",
              "topology": "demo_mechanism",
              "from": "base_datum",
              "to": "arm_tip",
              "closes": null,
              "units": "deg",
              "chain": [
                {
                  "edge": "base_thickness",
                  "name": "base plate thickness",
                  "edge_kind": "structural",
                  "from": "base_datum",
                  "to": "base_post_seat",
                  "dimension": "base_thickness",
                  "sign": 1,
                  "transform": "arm_linear_to_rotary",
                  "ratio": 2.5,
                  "weight": 2.5,
                  "value_nominal": 4.0,
                  "value_min": 3.98,
                  "value_max": 4.02,
                  "nominal": 10.0,
                  "min": 9.95,
                  "max": 10.05,
                  "units": "deg"
                },
                {
                  "edge": "post_height",
                  "name": "post height",
                  "edge_kind": "structural",
                  "from": "base_post_seat",
                  "to": "post_arm_pin",
                  "dimension": "post_height",
                  "sign": 1,
                  "transform": "arm_linear_to_rotary",
                  "ratio": 2.5,
                  "weight": 2.5,
                  "value_nominal": 10.0,
                  "value_min": 9.9,
                  "value_max": 10.1,
                  "nominal": 25.0,
                  "min": 24.75,
                  "max": 25.25,
                  "units": "deg"
                },
                {
                  "edge": "arm_pin_to_tip",
                  "name": "arm pin to tip",
                  "edge_kind": "structural",
                  "from": "post_arm_pin",
                  "to": "arm_tip",
                  "dimension": "arm_pin_to_tip",
                  "sign": 1,
                  "transform": "arm_linear_to_rotary",
                  "ratio": 2.5,
                  "weight": 2.5,
                  "value_nominal": 2.0,
                  "value_min": 2.0,
                  "value_max": 2.0,
                  "nominal": 5.0,
                  "min": 5.0,
                  "max": 5.0,
                  "units": "deg"
                }
              ],
              "nominal": 40.0,
              "worst_case_min": 39.7,
              "worst_case_max": 40.3,
              "worst_case_half": 0.3,
              "rss_center": 40.0,
              "rss_half": 0.254951,
              "rss_min": 39.745049,
              "rss_max": 40.254951
            },
            "layout": {
              "columns": 1,
              "rows": [
                {
                  "row": 0,
                  "kind": "node",
                  "id": "base_datum",
                  "column": 0,
                  "branch": false
                },
                {
                  "row": 1,
                  "kind": "edge",
                  "id": "base_thickness",
                  "column": 0,
                  "entered_at": "base_datum",
                  "left_at": "base_post_seat",
                  "closes_row": null,
                  "closes_column": null
                },
                {
                  "row": 2,
                  "kind": "node",
                  "id": "base_post_seat",
                  "column": 0,
                  "branch": false
                },
                {
                  "row": 3,
                  "kind": "edge",
                  "id": "post_height",
                  "column": 0,
                  "entered_at": "base_post_seat",
                  "left_at": "post_arm_pin",
                  "closes_row": null,
                  "closes_column": null
                },
                {
                  "row": 4,
                  "kind": "node",
                  "id": "post_arm_pin",
                  "column": 0,
                  "branch": false
                },
                {
                  "row": 5,
                  "kind": "edge",
                  "id": "arm_pin_to_tip",
                  "column": 0,
                  "entered_at": "post_arm_pin",
                  "left_at": "arm_tip",
                  "closes_row": null,
                  "closes_column": null
                },
                {
                  "row": 6,
                  "kind": "node",
                  "id": "arm_tip",
                  "column": 0,
                  "branch": false
                }
              ],
              "rails": [
                {
                  "column": 0,
                  "start": 0,
                  "end": 6
                }
              ],
              "links": []
            }
          },
          {
            "id": "demo_strut_branch",
            "title": "Base datum to strut end (the parallel path)",
            "topology": "demo_mechanism",
            "from": "base_datum",
            "to": "strut_end",
            "closes": null,
            "selection": [
              "base_thickness",
              "post_bushing_offset",
              "strut_length"
            ],
            "transforms": {},
            "source_file": "docs/topologies/study_demo_strut_branch.json",
            "notes": [],
            "provenance": {},
            "status": "ok",
            "error": null,
            "result": {
              "study": "demo_strut_branch",
              "title": "Base datum to strut end (the parallel path)",
              "topology": "demo_mechanism",
              "from": "base_datum",
              "to": "strut_end",
              "closes": null,
              "units": "mm",
              "chain": [
                {
                  "edge": "base_thickness",
                  "name": "base plate thickness",
                  "edge_kind": "structural",
                  "from": "base_datum",
                  "to": "base_post_seat",
                  "dimension": "base_thickness",
                  "sign": 1,
                  "transform": "identity",
                  "ratio": 1.0,
                  "weight": 1.0,
                  "value_nominal": 4.0,
                  "value_min": 3.98,
                  "value_max": 4.02,
                  "nominal": 4.0,
                  "min": 3.98,
                  "max": 4.02,
                  "units": "mm"
                },
                {
                  "edge": "post_bushing_offset",
                  "name": "post bushing offset",
                  "edge_kind": "structural",
                  "from": "base_post_seat",
                  "to": "post_strut_bushing",
                  "dimension": "post_bushing_offset",
                  "sign": 1,
                  "transform": "identity",
                  "ratio": 1.0,
                  "weight": 1.0,
                  "value_nominal": 6.0,
                  "value_min": 5.95,
                  "value_max": 6.05,
                  "nominal": 6.0,
                  "min": 5.95,
                  "max": 6.05,
                  "units": "mm"
                },
                {
                  "edge": "strut_length",
                  "name": "strut length",
                  "edge_kind": "structural",
                  "from": "post_strut_bushing",
                  "to": "strut_end",
                  "dimension": "strut_length",
                  "sign": 1,
                  "transform": "identity",
                  "ratio": 1.0,
                  "weight": 1.0,
                  "value_nominal": 8.0,
                  "value_min": 7.9,
                  "value_max": 8.1,
                  "nominal": 8.0,
                  "min": 7.9,
                  "max": 8.1,
                  "units": "mm"
                }
              ],
              "nominal": 18.0,
              "worst_case_min": 17.83,
              "worst_case_max": 18.17,
              "worst_case_half": 0.17,
              "rss_center": 18.0,
              "rss_half": 0.113578,
              "rss_min": 17.886422,
              "rss_max": 18.113578
            },
            "layout": {
              "columns": 1,
              "rows": [
                {
                  "row": 0,
                  "kind": "node",
                  "id": "base_datum",
                  "column": 0,
                  "branch": false
                },
                {
                  "row": 1,
                  "kind": "edge",
                  "id": "base_thickness",
                  "column": 0,
                  "entered_at": "base_datum",
                  "left_at": "base_post_seat",
                  "closes_row": null,
                  "closes_column": null
                },
                {
                  "row": 2,
                  "kind": "node",
                  "id": "base_post_seat",
                  "column": 0,
                  "branch": false
                },
                {
                  "row": 3,
                  "kind": "edge",
                  "id": "post_bushing_offset",
                  "column": 0,
                  "entered_at": "base_post_seat",
                  "left_at": "post_strut_bushing",
                  "closes_row": null,
                  "closes_column": null
                },
                {
                  "row": 4,
                  "kind": "node",
                  "id": "post_strut_bushing",
                  "column": 0,
                  "branch": false
                },
                {
                  "row": 5,
                  "kind": "edge",
                  "id": "strut_length",
                  "column": 0,
                  "entered_at": "post_strut_bushing",
                  "left_at": "strut_end",
                  "closes_row": null,
                  "closes_column": null
                },
                {
                  "row": 6,
                  "kind": "node",
                  "id": "strut_end",
                  "column": 0,
                  "branch": false
                }
              ],
              "rails": [
                {
                  "column": 0,
                  "start": 0,
                  "end": 6
                }
              ],
              "links": []
            }
          },
          {
            "id": "demo_ambiguous",
            "title": "Both paths at once (raises BranchAmbiguity)",
            "topology": "demo_mechanism",
            "from": "base_datum",
            "to": "arm_tip",
            "closes": null,
            "selection": [
              "base_thickness",
              "post_height",
              "arm_pin_to_tip",
              "post_bushing_offset",
              "strut_length"
            ],
            "transforms": {},
            "source_file": "docs/topologies/study_demo_ambiguous.json",
            "notes": [],
            "provenance": {},
            "status": "error",
            "error": {
              "type": "BranchAmbiguity",
              "message": "study 'demo_ambiguous' reaches node 'base_post_seat' ('base / post seat') with 2 selected edges still unused: 'post_height' ('post height'), 'post_bushing_offset' ('post bushing offset'). That is a branch point, and which path binds is a mechanics decision this tool does not make. Drop the branches this study is not about from `selection`, or split it into one study per path."
            },
            "result": null,
            "layout": null
          }
        ]
      }
      ],
      // Empty on purpose: an orphan study would put a banner alarm on screen in
      // ?mock=1, where nothing is wrong. VA.orphanStudyAlarms has its own test,
      // which builds one inline.
      orphan_studies: [],
    };
  };

  // The MemoryAdapter options topology.html?mock=1 boots with. The crops index
  // and the one demo PNG are fixtures.js's, not a second copy: the three
  // crop_keys above address exactly its `demo_joint` entries, so the resolved /
  // unresolvable / stale-index trio is the same data the stack viewer's demo
  // renders.
  VA.demoTopologyFixture = function () {
    var stackDemo = VA.demoFixture();
    return {
      startState: VA.STATE.READY,
      topologies: VA.demoTopologyProjection(),
      crops: stackDemo.crops,
      images: stackDemo.images,
    };
  };
})(window.ViewerApp = window.ViewerApp || {});
